name: IF Media
favicon: null
layout_spectrum: 0.31700522638857365
typography_spectrum: 0.7561728213913739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7340573265682906
  lightness: 0.21185292699374259
  saturation: 0.6369319767691195
  rhythmicContrast: 0.6738503796514124
purpose: []
